export const ja = {
  translations: {
    'Navigation 1': 'ホワイトペーパー',
    'Navigation 2': '開発者',
    'Navigation 3': 'コアテクノロジー',
    'Navigation 4': 'チーム',
    'Navigation 5': 'お問い合わせ',
    'Hero Title': 'スマートイーサネットプロトコル',
    'Hero Description': 'プログラム可能なパケットを利用し、セキュリティ、プライバシー、ネットの中立性を強化する新しいブロックチェーンプロトコル',
    'CTA Prompt': 'SDKへのアーリーアクセスを利用する',
    'CTA 1': 'コミュニティに参加する',
    'CTA 2': '読むホワイトペーパー',
    'M1 Title': 'コアテクノロジー',
    'M1 Description': 'イーサネットレベルまで設計されたMarconiプロトコルは、プライバシー、セキュリティ、ネットの中立性、アップグレード性を向上させる分散ネットワーキングスタックを強化します。',
    'M1 Sub1 Title': 'イーサネットレベルでの暗号化',
    'M1 Sub1 Description': 'OSIモデルのレイヤ2に構築される安全な通信パイプにより、SSLやTLSのみを使用した場合よりも安全性の高いパケットレベルの暗号化を提供します',
    'M1 Sub2 Title': 'プログラム可能なパケット',
    'M1 Sub2 Description': 'ネットワークパケットに直接アクセスできる分散アプリにより、高価なカスタムハードウェアを使わずに、ネットワーク管理とセキュリティ機能が利用可能になります',
    'M1 Sub3 Title': 'ブランチチェーン',
    'M1 Sub3 Description': 'ブランチの利用が可能なブロックチェーンにより、特定地域内の少数の企業によって管理される従来のインフラストラクチャがなくても、新しい分散型ネットワークを構築できます',
    'Learn More Prompt': 'Marconiプラットフォームの詳細',
    'Learn More CTA': 'ホワイトペーパーを読む',
    'M2 Title': '使用事例',
    'M2 Sub1 Title': 'トークンからブロックチェーンへの移行',
    'M2 Sub1 Description': 'ブロックチェーンを有効にすることによって、トークンによるユーティリティの利用が可能になる独自のチェーンにトークンプロジェクト（ERC20など）を移行します',
    'M2 Sub2 Title': '仮想化ブロックチェーン',
    'M2 Sub2 Description': '安全なブロック作成と永続性を提供するMarconiネットワークを活用した新しいブロックチェーンを簡単に利用できます',
    'M2 Sub3 Title': 'ダイナミックネットワーク',
    'M2 Sub3 Description': '実環境や緊急避難的な環境にダイナミックネットワークを迅速に展開します。アクションを後で確認できるように元帳にネットワーク活動を記録します',
    'M2 Sub4 Title': 'セキュリティアプリ',
    'M2 Sub4 Description': 'アンチフィッシング、アンチマルウェア、侵入防止システム、dVPNなどの分散型セキュリティアプリを作成します',
    'M2 Sub5 Title': 'ネットワーク管理アプリ',
    'M2 Sub5 Description': 'ネットワーク負荷分散、ネットワークトポロジーの変更、IOTデバイス管理のための管理アプリケーションを作成します',
    'M2 Sub6 Title': 'IOTデバイス管理',
    'M2 Sub6 Description': 'IOTデバイス管理のセキュリティ、プライバシー、接続の問題に対処するアプリケーションを開発します',
    'M3 Title': '開発者',
    'M3 Header 1': 'アプリケーション',
    'M3 Description 1': 'ネットワークパケットにアクセスできるチューリング完全言語のMarconi Scriptを使用して、分散型アプリケーションを記述します。',
    'M3 Header 2': 'ライブラリ',
    'M3 Description 2': '分散型アプリをグローバルチェーンやブランチチェーンに送信することによって、パブリックネットワークやプライベートネットワークを構築できます。',
    'M3 Description 3': 'APIを利用することによって、トラフィックルーティング、パケット分析、パターン認識、ブランチチェーンの作成、トークンの移行が可能になります。',
    'M3 CTA Prompt': 'SDKへのアーリーアクセスを利用する',
    'M3 CTA 1': 'コミュニティに参加する',
    'M3 CTA 2': 'Gitアクセスをリクエストする',
    'M3 Header 3-1': 'サンプル',
    'M3 Header 3-2': 'コード',
    'M3 Tab1 Title': 'ネットワークの作成',
    'M3 Tab1 Description': 'わずか数行のコードで新しいブロックチェーンを強化できます',
    'M3 Tab2 Title': 'ネットワーク管理',
    'M3 Tab2 Description': 'ネットワークで許可されるトラフィックの種類を決めるポリシーを確立できます',
    'M3 Tab3 Title': 'アンチフィッシング',
    'M3 Tab3 Description': 'Unicode文字によるURLのマスカレードのようなフィッシング攻撃がないかネットワークトラフィックを分析します',
    'Team Bio Title': 'コアチーム',
    'Jong Title': 'ブロックチェーン',
    'Jong Description': 'Bitcoinマイナー、ブロックチェーンの開発者、投資家（2011年以降）。最初のマルチブロックチェーンエクスプローラーの1つであるHashLayer（2014～15）の創設者。ネットワークテクノロジーを構築するGoogleのチームを率いる。南カリフォルニア大学卒（コンピュータサイエンス）。',
    'Darryl Title': 'ネットワーキング',
    'Darryl Description': 'Googleのネットワークと検索システムを最適化するエンジニアリングチームを率いる。また、Qualcommでソフトウェアデファインドの無線ドライバーおよびネットワークドライバーを開発。南カリフォルニア大学卒（コンピュータサイエンス）。',
    'Albert Title': 'セキュリティ',
    'Albert Description': 'Credit Karmaの消費者および内部データを保護するためのセキュリティシステムと暗号化サービスを開発。ソフトウェアエンジニアリング -  UWaterloo。',
    'Di Title': 'プラットフォーム',
    'Di Description': 'Credit KarmaとService Nowでビッグデータプラットフォームを作成したエンジニアリングチームを率いる。前職はMicrosoftやIntelなどの大手IT企業のソフトウェアエンジニア。ソフトウェアエンジニアリング -  UWaterloo。',
    'Kyle Title': 'インフラストラクチャ',
    'Kyle Description': 'Googleにおいて高密度およびワイヤレスネットワークを拡張するためのデータセンターインフラストラクチャを構築。ガビラン大学卒（コンピュータサイエンス）、カリフォルニア大学バークレー校卒（BA）。',
    'Peter Title': '運用',
    'Peter Description': '2014年以降ブロックチェーン投資家。Zyngaなどのスタートアップ企業やMicrosoftなどの企業でエグゼクティブおよび管理職。ウォータールー大学卒（コンピュータエンジニアリング）、ペンシルベニア大学ウォートン・スクール卒（経営学修士）。',
    'Chris Title': '製品とSDK',
    'Chris Description': 'AppleでMac OS XやObjective-C用のAPIおよびSDKを開発。製品チームを率い、Dropboxなどのスタートアップ企業でアプリをリリース。カリフォルニア大学サンディエゴ校卒（コンピュータサイエンス）、ペンシルベニア大学ウォートン・スクール卒（経営学修士）。',
    'Advisors Title': 'アドバイザー',
    'George Title': 'WeTrustのCEO',
    'George Description': 'Vitalik Buterin、Bo Shen、Fenbushi Capitalの支援を受けたブロックチェーン保険プラットフォームWeTrustの共同設立者。前職はGoogleとMcKinsey。スタンフォード大学卒（理学修士）。',
    'Matt Title': 'Originの共同設立者',
    'Matt Description': 'EthereumとIPFSを使用してシェアリングエコノミー市場を創出するプロトコルであるOriginを共同設立。Pantera Capitalの支援。前職はGoogle。スタンフォード大学卒（電気工学およびマスター・オブ・サイエンス）。',
    'Jay Title': 'Spoke社CEO',
    'Jay Description': 'モバイルプラットフォームのAppurify（Googleが買収）とワークプレースAIのSpoke（GreylockとAccelの支援を得て）を共同設立。マイクロプロセッサの信頼性における熟練リサーチャー。インド工科大学卒（電気工学）、イリノイ大学アーバナ・シャンペーン校卒（博士号）。',
    'Joyce Title': 'ML & IOT研究員',
    'Joyce Description': 'IOTを用いた機械学習の快適性予測の先駆的研究者および著者。Berkeley Labsのスマートグリッドの研究者を務める。ウォータールー大学卒（エンジニアリング）、カリフォルニア大学バークレー校卒（博士号）。',
    'Glenn Title': 'シリアルアントレプレナー',
    'Glenn Description': 'PDI（<1>Shrek</1>シリーズと<3>Madagascar</3>シリーズのプロデューサー）とVanEdge Capitalを共同設立。DreamWorks InteractiveのCEO。Snapchat、Zynga、Citigroupを含む企業のアドバイザー。',
    'Stefan Title': 'ファイナンス',
    'Stefan Description': 'PlentyのシニアVP（ソフトバンクから2億2,600万ドル調達）、ProsperWorks（DHVCから8,600万ドル調達）、Harvest Power（Kleiner Perkinsから2億2,400万ドル調達）。カリフォルニア大学バークレー校卒（経済）、ペンシルベニア大学ウォートン・スクール卒（経営学修士）',
    'Tom Title': 'BitGoのCSO',
    'Tom Description': 'Bitgoのセキュリティー専門家とセキュリティ最高責任者-ブロックチェーンセキュリティプラットフォームの先導、 マルチシグマ技術のパイオニア。 NeustarとDocuSignの元CSO。 ハーバード大学のMPA。',
    'Join Modal Title': 'Marconi SDKと最新の製品アップデートへのアーリーアクセスを利用する',
    'Join Modal Name': '氏名*',
    'Join Modal Organization': '組織',
    'Join Modal Description': 'ご興味を持たれた理由をお聞かせください。',
    'Thanks Modal title': 'ありがとうございました。',
    'Thanks Modal welcome': 'Marconiコミュニティへようこそ',
    'GDPR Confirm': 'メールで製品のアップデートを受け取りたいです。',
    'GDPR Text': 'マルコーニ財団が更新情報を送信するために個人情報を保存することを理解します。プライバシーポリシーを読解しました。電子メールメッセージを通じて「購読中止」オプションを選択することにより、製品や製品のアップデートを受信しないようにすることができます。 解除すると、個人情報は収集されず、以前に収集された個人情報は削除されます。',
    'White Paper Link': 'https://docsend.com/view/5zragmb',
    'Investors Title': '投資家'
  }
};